### PR TITLE
support for collections

### PR DESCRIPTION
**Pull request by tbranyen**
support for collections, contains tests, still need to use in production to see how this may break down.

### CODE REVIEW

**Comment by tbranyen** [comment]
Just wanna say that I tried this out in my current app and it worked flawlessly.  So amazingly baller to filter collections :D

**Comment by mxriverlynn** [comment]
just read through the code - looks great! :) thank you for the attention to detail in updating the readme, especially. 

one scenario popped into my mind that i didn't see covered in the specs, after reading through it: what happens when you remove a model from the collection and then restart? i would expect it to re-add that model to the collection. based on the way the collection `.toJSON()` is called to store the data, i would think that it works this way. 

i'd like to see a spec that covers this scenario, whether or not it re-adds or leaves the removed model out.

**Comment by tbranyen** [comment]
If I'm understanding you correctly, yes, it definitely works that way.  I'll create a test to mock that situation and add it in.

**Comment by tbranyen** [comment]
@derickbailey hope this test is what you were looking for.

**Comment by mxriverlynn** [comment]
exactly what i was hoping for! :)

i'll get this pulled in and have a new release out soon - tonight or tomorrow.

thanks for all the work on this!

**Comment by mxriverlynn** [comment]
finally got this merged and released!

**Comment by tbranyen** [comment]
Awesome! You're the man, glad I could contribute.

**Pull request merged**
